name: prestashop-fpm-example
services:
  prestashop:
    image: prestashop/prestashop:fpm-latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PS_DOMAIN=localhost:8000
      - PS_DEMO_MODE=1
    expose:
      - 9000

  # TODO: fix link between prestashop & nginx (eg: static assets...)
  nginx:
    image: nginx:latest
    healthcheck:
      test: [ "CMD", "curl", "-is", "http://localhost:80" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      prestashop:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80

  mysql:
    image: mariadb:lts
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop


