---
name: Publish containers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# TODO: nightly -> cron ?

env:
  REGISTRY: docker.io
  PLATFORM: 'linux/amd64,linux/arm64'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          use: true
          platforms: ${{ env.PLATFORM }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install dependencies
        shell: bash
        run: apt install jq curl

      - name: Build Docker images
        shell: bash
        run: ./build.sh

      - name: Push Docker images
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          echo "WIP"
          docker image ls
