---
name: Publish containers

on:
  push:
    branches: master

env:
  REGISTRY: docker.io

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        with:
          use: true
#          platforms: ${{ env.TARGET_PLATFORMS }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Install dependencies
#        run: apt install jq

      - name: Build Docker images
        run: echo "WIP"

      - name: Push Docker images
        run: echo "WIP"
